# .github/workflows/master_scepmanvxn.yml

name: Build and deploy Azure Function - scepmanvxn

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # ou o path do seu código se não estiver na raiz

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy PowerShell Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'scepmanvxn'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
